# Generated by Django 4.0.6 on 2022-07-28 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='NAME')),
                ('phone_no', models.CharField(max_length=12)),
                ('pincode', models.CharField(max_length=6, verbose_name='PINCODE')),
                ('state', models.CharField(max_length=6, verbose_name='STATE')),
                ('city', models.CharField(max_length=6, verbose_name='CITY')),
                ('house_no', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
