# Generated by Django 4.0.6 on 2022-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20, verbose_name='CITY'),
        ),
    ]
