# Generated by Django 4.0.6 on 2022-07-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Addresses', '0002_alter_address_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
