# Generated by Django 4.0.6 on 2022-07-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Addresses', '0003_rename_user_id_address_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
