# Generated by Django 4.0.1 on 2022-07-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cart', '0002_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total_items',
        ),
    ]
