# Generated by Django 4.0.1 on 2022-07-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cart', '0003_remove_cartitems_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
